#!/bin/bash

function ban {
echo "ban"

echo $API_USER
echo $API_ENCR_PASS
echo $HOSTNAME
echo $IP

echo "Add host def:"
sed -e "s/API_USER_TEMPL/$API_USER/" \
    -e "s/API_ENCR_PASS_TEMPL/$API_ENCR_PASS/" \
    -e "s/HOSTNAME_TEMPL/$HOSTNAME/" \
    -e "s/IP_TEMPL/$IP/" \
    "$XG_FAIL2BAN_LOCATION/addOfHostDef.templ" > /tmp/xg_fail2ban-$IP-$$.xml

echo "Add firewall def:"
sed -e "s/API_USER_TEMPL/$API_USER/" \
    -e "s/API_ENCR_PASS_TEMPL/$API_ENCR_PASS/" \
    -e "s/HOSTNAME_TEMPL/$HOSTNAME/" \
    -e "s/IP_TEMPL/$IP/" \
    -e "s/XG_ACTION_TEMPL/$XG_ACTION/" \
    -e "s/XG_STATUS_TEMPL/$XG_STATUS/" \
    "$XG_FAIL2BAN_LOCATION/addOfFirewallDef.templ" >> /tmp/xg_fail2ban-$IP-$$.xml
}

function unban {
echo "unban"

echo $API_USER
echo $API_ENCR_PASS
echo $HOSTNAME
echo $IP

echo "Delete firewall def:"
sed -e "s/API_USER_TEMPL/$API_USER/" \
    -e "s/API_ENCR_PASS_TEMPL/$API_ENCR_PASS/" \
    -e "s/HOSTNAME_TEMPL/$HOSTNAME/" \
    -e "s/IP_TEMPL/$IP/" \
    "$XG_FAIL2BAN_LOCATION/deleteOfFirewallDef.templ" > /tmp/xg_fail2ban-$IP-$$.xml

echo "Delete host def:"
sed -e "s/API_USER_TEMPL/$API_USER/" \
    -e "s/API_ENCR_PASS_TEMPL/$API_ENCR_PASS/" \
    -e "s/HOSTNAME_TEMPL/$HOSTNAME/" \
    -e "s/IP_TEMPL/$IP/" \
    "$XG_FAIL2BAN_LOCATION/deleteOfHostDef.templ" >> /tmp/xg_fail2ban-$IP-$$.xml
}

function help {
    echo ""
    echo "Configure the file /etc/xg_fail2ban.conf,"
    echo "And use like:"
    echo "xg_fail2ban ban 1.2.3.4"
    echo " or"
    echo "xg_fail2ban unban 1.2.3.4"
    echo ""
    exit 1
}

if [ -f "/etc/xg_fail2ban.conf" ]; then
    source /etc/xg_fail2ban.conf
else 
    help
fi

IP=$2

case $1 in "") help; esac

case $1 in "ban") ban; esac

case $1 in "unban") unban; esac

case $2 in "") help; esac

echo "and finally upload the generated xml, if the script made t all the way here"
echo "the name of the generated file: /tmp/xg_fail2ban-$IP-$$.xml"
# uncomment the below line to *actually* apply the XML to the XG over the API
# curl -v -k $XG_URL/webconsole/APIController -F "reqxml=</tmp/xg_fail2ban-$IP-$$.xml"
